PROCEDURE VAR_DECLARE
   *** MENU VARIABLES ***
   PUBLIC ARRAY XMENUVAR(1,3)
   *** MENU VARIABLES ***
   
   PUBLIC ARRAY XEDCVAR(1,37)
   
   *** LOG FILE VARIABLES ***
   PUBLIC ARRAY XARBLOGVAR(1,2)    && USE DHL LOG / PATH  && AFTER DONE CONVER TO DHL
   PUBLIC ARRAY XFDXLOGVAR(1,2)    && USE FEDEX LOG / PATH
   PUBLIC ARRAY XUPSLOGVAR(1,2)    && USE UPS LOG / PATH
   PUBLIC ARRAY XUSPSLOGVAR(1,2)   && USE USPS LOG / PATH
   PUBLIC ARRAY XLOGVAR(1,5)       && REQUEST 1 / REQUEST 2 / RESPONSE 1 / RESPONSE 2 / TRACK #
   
   PUBLIC ARRAY XABNVAR(1,8)    && DHL      - LOGIN/PASSWORD/SHIPKEY/BLANK/BLANK/BLANK/USE AIRBORNE/OPTION
   PUBLIC ARRAY XFDXVAR(1,8)    && FEDEX    - LOGIN/PASSWORD/SHIPKEY/BLANK/BLANK/BLANK/USE FEDEX/OPTION
   PUBLIC ARRAY XUPSVAR(1,9)    && UPS      - LOGIN/PASSWORD/ACCESSKEY/VALIDATE/REFERENCE1/REFERENCE2/USE UPS/OPTION/SERVER
   PUBLIC ARRAY XUSPSVAR(1,9)   && USPS     - LOGIN/PASSWORD/ACCESSKEY/BLANK/BLANK/BLANK/USE USPS/OPTION/SERVER
   
   PUBLIC ARRAY XDEVICEVAR(1,69)   && PERIPHERAL SETTING
   
   *****************************
   *** ONLY USE IN INTERFACE ***
   PUBLIC ARRAY XBYPASSUSPS(1,1)  && BYPASS ADDRESS CHECK AND SHIP PROCEDURE
   *** ONLY USE IN INTERFACE ***
   *****************************
   
   *INTERFACE_ON,INTERFACE_TRY
   PUBLIC ARRAY XIDVAR(1,13)    && IOPROMPT/PKGID/INVNUM/ORDERNUM/PONUM/DEPTNUM/
                                && REFERENCE1/REFERENCE2/REFERENCE3/TRANSNUM/PICKER/PACKER
   PUBLIC ARRAY XMISCVAR(1,4)   && MISCVAR1/MISCVAR2/MISCVAR3/MISCVAR4
   PUBLIC ARRAY XCARVAR(1,10)   && CARRCODE/CARRIER/CARRSRVC/CARRSRVCTYP/PKGTYPE/PKGCODE/PCKUPTYPE/PCKUPCODE/DELVDAY/DELVDATE
   PUBLIC ARRAY XTRANSVAR(1,2)  && TRANSLATED CARRIER CODE/TRANSLATED COUNTRY CODE  -  *** INTERFACE ONLY ***
   PUBLIC ARRAY XWGTVAR(1,3)    && BILLWGT/SHIPWGT/TOTWGT - WEIGHT VARIABLES
   PUBLIC ARRAY XTOTWGTVAR(1,1) && TOTAL WGT - DOC SUMMARY ONLY
   PUBLIC ARRAY XCNTVAR(1,2)    && PKGCNT/TOTPKGCNT  && NUMERIC
   PUBLIC ARRAY XDATEVAR(1,2)   && PKGDATE/DELVDATE
   PUBLIC ARRAY XTIMEVAR(1,2)   && PKGTIME/DELVTIME
   PUBLIC ARRAY XNUMVAR(1,14)   && SHIPNUM/ZONE/ROUTECODE/SHPMNTNUM/TRACKNUM/ORGINSTAT/CODTRACKNUM/ASTRABARCODE/CODASTRABARCODE
                                && FORMID/FORMIDCOD/MASTFORMID/SRVCCOMMIT/CODSRVCCOMMIT
                                
   PUBLIC ARRAY XSHIPVAR(1,14)  && CUSTNUM/NAME/ATTN/ADDR1/ADDR2/ADDR3/CITY/ST/ZIP/COUNTRY/CNTRYCODE/PHONE/FAX/EMAIL ADDRESS
   PUBLIC ARRAY XBILLVAR(1,15)  && BILLTYPE/BILLACCT/NAME/ATTN/ADDR1/ADDR2/ADDR3/CITY/ST/ZIP/
                                && COUNTRY/CNTRYCODE/PHONE/FAX/BILLNUM - THIRD PARTY, COLLECT BILLING
   
   PUBLIC ARRAY XPREBILLVAR(1,14) && BILLACCT/NAME/ATTN/ADDR1/ADDR2/ADDR3/CITY/ST/ZIP/
                                  && COUNTRY/CNTRYCODE/PHONE/FAX/FEDEX METER NUMBER - PREPAID BILLING
   
   PUBLIC ARRAY XRETVAR(1,10)    && NAME/ATTN/ADDR/CITY/ST/ZIP/COUNTRY/COUNTRY CODE/PHONE/FAX - RETURN ADDRESS
   
   PUBLIC ARRAY XSPECVAR(1,15)  && ADDHAND/HANDCHG/CODFLAG/CODSHIP/CODSECURE/INSFLAG/RETSRVC/SATDELV/SATPCKUP/  && LOGICAL
                                && SHPNOTIFY1/SHPNOTIFY2/DELVCONFRM/OVERSIZE/DIM/RESIDNTIAL
                                && REMOVED - (16)HAZMAT/(17)HOLD AT CARRIER/(18)ASSET PROTECTION
   PUBLIC ARRAY XSPECCHAR(1,21) && HANDRATE/RETLAB/CALLTAG/RETDESC/
                                && SHPMETHOD1/SHPCOMP1/SHPCONT1/SHPPHONE1/SHPEMLFAX1/SHPMEMO1/
                                && SHPMETHOD2/SHPCOMP2/SHPCONT2/SHPPHONE2/SHPEMLFAX2/SHPMEMO2/
                                && DELVSIGNTR/OVERSIZTYP/DIMDESC/DIMINST/INTCUSTOMDESC  && CHARACTER
   PUBLIC ARRAY XSPECCHG(1,11)  && HANDFEE/CODAMT/CODCHG/INSAMT/INSCHG/CALLCHG/DIMLENGTH/DIMWIDTH/DIMHEIGHT/DIMWEIGHT/
                                && INCUSTOMVALUE
                                && REMOVED - (12)ASSETPROTECTIONAMT/(13)ASSETPROTECTIONCHG  && NUMERIC
   PUBLIC ARRAY XOVERVAR(1,4)   && OVERRIDEZIP/OVERRIDEZIPST/OVERRIDEZIPROUTE/OVERRIDEEXPFRIDAY
   PUBLIC ARRAY XRATEVAR(1,3)   && SRVC CHARGE/TRANS CHARGE/TOT CHARGE
   PUBLIC ARRAY XCHGVAR(1,9)    && I_TRANSCHG/I_SRVCCHG/TRANSCHG/SRVCCHG/TOTALCHG/INVTOTAL/IPTRANSCHG/P_TRANSCHG/P_TOTALCHG  && NUMERIC
   PUBLIC ARRAY XCHGCODE(1,6)   && I_TRANSCOD/I_SRVCCODE/TRANSCODE/SRVCCODE/TOTALCODE/BILLWGTCOD       && CHARACTER
   PUBLIC ARRAY XTOTCHGVAR(1,6) && SERVICE CHGS/HANDLING CHARGES/DISC FREIGHT CHGS/DISC TOTAL CHGS/PUB FREIGHT CHGS/ PUB TOT CHARGES
   
   PUBLIC ARRAY XLABVAR(1,10)    && LABELCODE/LABELIMAGE/LABELSGNTR/SHMNTDGST/LABELHTML/LABELDOC/CODLABELIMAGE/INTLABELIMAGE/DOC SUMMARY/EXPIMAGE  && CHARACTER
   
   *** INTERNATIONAL VARIABLES
   PUBLIC ARRAY XINTLVAR(1,25)  && INVNUM/FILENUM/REFNUM/CUSTPONUM/CARRNUM/USPPIEIN/ECCNNUM/LICNUM/COMMENTS1/COMMENTS2
                                && COMMENTS3/COFUD/MODETRANS/INCOTERM/LTRCREDIT/STATEMENT/SIGNATURE/SHIPTAXID/CONTAXID
                                && DOCPRINTER/PRNTENDOPT/ORGINCOUNT/COMMTITLE/DUTYTAX/DUTYTAXACCT  - CHARACTER
   PUBLIC ARRAY XINTLVAL(1,5)   && NUMOFPACK/NUMOFCOPYS/OTHERCHARGES/INSCHARGES/TOTALBOXWGT   - NUMERIC
   PUBLIC ARRAY XINTLDATEVAR(1,1)   && LICEXPDATE         - DATE
   PUBLIC ARRAY XINTLLOGICVAR(1,6)  && RELATED/SOLD/PARTIES/EXTRANS/HAZ/PRINTEND  - LOGICAL
   
   PUBLIC ARRAY XINTLBILLVAR(1,12)  && BILLCOMP/BILLATTN/BILLADDR1/BILLADDR2/BILLADDR3/BILLCITY/BILLST/BILLZIP/BILLCOUNT/BILLCNTCDE/BILLPHONE/BILLFAX
   PUBLIC ARRAY XINTLFRWDVAR(1,12)  && FRWDCOMP/FRWDATTN/FRWDADDR1/FRWDADDR2/FRWDADDR3/FRWDCITY/FRWDST/FRWDZIP/FRWDCOUNT/FRWDCNTCDE/FRWDPHONE/FRWDFAX
   PUBLIC ARRAY XINTLPRODVAR(1,4)   && PRODCODE/PRODDESC/PRODUOM/HARMCODE
   PUBLIC ARRAY XINTLPRODVAL(1,3)   && PRODQTY/PRODPRICE/PRODWGT
   
   *** ADDED 02/23/2003 FOR CARRIER DISCOUNTS
   PUBLIC ARRAY XARBDIS(1,20)  && AIRBORNE
   PUBLIC ARRAY XFDXDIS(1,30)  && FEDEX
   PUBLIC ARRAY XUPSDIS(1,30)  && UPS
   PUBLIC ARRAY XUPSDIS(1,30)  && USPS
   
   *** REPEAT LAST SHIPMENT VARIABLES
   PUBLIC ARRAY XREPSHIPVAR(1,13)  && CUSTNUM/NAME/ATTN/ADDR1/ADDR2/ADDR3/CITY/ST/ZIP/COUNTRY/CNTRYCODE/PHONE/FAX
   PUBLIC ARRAY XREPCARVAR(1,6)    && CARRCODE/CARRIER/CARRSRVC/CARRSRVCTYP/PKGTYPE/PKGCODE
      
   *** MULTI-BOX SHIPMENT VARIABLES
   PUBLIC ARRAY XMULTICARVAR(1,4)   && CARRCODE/CARRIER/CARRSRVC/CARSRVCTYPE
   PUBLIC ARRAY XMULTIREFVAR(1,3)   && REF1/REF2/REF3
   
   PUBLIC ARRAY XMULTIWGTVAR(1,1)   && SHIPWGT
   PUBLIC ARRAY XMULTISPECVAR(1,8)  && INS FLAG/COD FLAG/COD SECURE/COD SHIP/SAT DELV/SATPCKUP/HAND FLAG/OVERSIZE
   PUBLIC ARRAY XMULTISPECCHAR(1,2)  && HAND FEE - F = FLAT / P = PERCENT - OVERSIZE TYPE
   PUBLIC ARRAY XMULTISPECCHG(1,5)  && INS AMT/INS CHG/COD AMT/COD CHG/HAND CHG
   PUBLIC ARRAY XMULTIBOXVAR(1,1)   && PACKAGE COUNT
   PUBLIC ARRAY XMULTICHGVAR(1,3)   && TRANSCHG/SRVCCHG/TOTCHG
   *** MULTI-BOX SHIPMENT VARIABLES
   
   PUBLIC ARRAY XSTATVAR(1,2)
   PUBLIC ARRAY XPATHVAR(1,5)      && PATHS
   PUBLIC ARRAY XSHIPPERVAR(1,1)
ENDPROC